services:
  podcast-api:
    container_name: podcast-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./api:/app
    expose:
      - 8000
    networks:
      - db-network
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - podcast-api
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
