services:
  podcast-api:
    container_name: podcast-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./api:/app
    expose:
      - 8000
    networks:
      - db-network

  client:
    container_name: podcast-client
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile.dev
    volumes:
      - ./client:/app/client
      - node_modules:/app/client/node_modules
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.dev/conf.d:/etc/nginx/conf.d
    depends_on:
      - podcast-api
    networks:
      - db-network


volumes:
  node_modules:

networks:
  db-network:
    driver: bridge