version: "3.8"

services:
  podcast-api:
    container_name: podcast-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app
    expose:
      - 8000
