# 使用 Node.js 官方镜像作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app/client

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY . .



# 暴露 Next.js 默认端口
EXPOSE 3000

# 启动应用
CMD ["npm", "run","dev"]
